apiVersion: apps/v1
kind: Deployment
metadata:
  name: openjdk17-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openjdk17-app
  template:
    metadata:
      labels:
        app: openjdk17-app
    spec:
      containers:
      - name: my-app-container
        image: avherrera/openjdk17:1.0
        ports:
        - containerPort: 80
      # para ACR
      # imagePullSecrets:
      # - name: acr-secret
