name: Build and Deploy to AKS

# eventos
on:
  push:
    branches:
      - main

# jobs en el flujo de trabajo
jobs:
  build-app:
    # entorno
    runs-on: self-hosted

    # pasos
    steps:
    - name: Checkout of source code
      uses: actions/checkout@v2

    - name: Check versions
      run: bash pre-init.sh
    
    - name: Azure login
    #   run: az login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    # aks kubeconfig
    - name: Set up kubectl
      run: cp k8s/config ~/.kube/config

    # deplot to aks
    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    # get pods
    - name: Validate Deployment
      run: kubectl get pods

    # Rollback on Failure
    - name: Rollback on Failure
      if: failure()
      run: |
        # Obtener el número de revisión anterior
        PREVIOUS_REVISION=$(kubectl rollout history deployment/openjdk17-deployment --revision=0 --output=jsonpath={.revision})

        # Realizar el rollback
        kubectl rollout undo deployment/openjdk17-deployment --to-revision=${PREVIOUS_REVISION}