name: Build and Deploy to AKS

# eventos
on:
  push:
    branches:
      - main

# jobs en el flujo de trabajo
jobs:
  build-app:
    # entorno
    runs-on: self-hosted
    
    # variables de entorno
    # env:
    #   AZURE_KEYVAULT_URL: ${{ secrets.AZURE_KEYVAULT_URL }}
    #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #   AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    # pasos
    steps:
    - name: Checkout of source code
      uses: actions/checkout@v2

    - name: Check versions
      run: bash pre-init.sh
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
      
    # - name: config
    #   run: bash config.sh

    # - name: Clean
    #   run: bash pre-build.sh

    # - name: Build and push
    #   run: bash docker-build-push.sh

    - name: Set up kubectl
      run: mkdir -p ~/.kube \ 
        cp k8s/config ~/.kube/config

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Validate Deployment
      run: kubectl get pods

    #- name: destroy
    # run: destroy.sh
